import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

class ResumeAnalysisService {
  /// Generates a PDF file containing the AI-generated resume and coding summaries.
  /// Returns the path to the stored PDF file.
  static Future<String> generateSummaryPdf({
    required String name,
    required String resumeSummary,
    required String codingSummary,
    Map<String, dynamic>? extraDetails,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('CodeSphere Resume Analysis', 
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo)),
                  pw.Text(DateTime.now().toString().split(' ')[0], 
                    style: const pw.TextStyle(color: PdfColors.grey)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            
            pw.Header(level: 1, text: 'Candidate Profile: $name'),
            pw.Paragraph(
              text: resumeSummary,
              style: const pw.TextStyle(lineSpacing: 1.5),
            ),
            pw.SizedBox(height: 20),

            pw.Header(level: 1, text: 'Competitive Programming & Problem Solving'),
            pw.Paragraph(
              text: codingSummary,
              style: const pw.TextStyle(lineSpacing: 1.5),
            ),
            pw.SizedBox(height: 20),

            if (extraDetails != null) ...[
               pw.Header(level: 1, text: 'Platform Statistics'),
               pw.Bullet(text: 'LeetCode: ${extraDetails['leetcode'] ?? 'N/A'}'),
               pw.Bullet(text: 'GitHub: ${extraDetails['github'] ?? 'N/A'}'),
               pw.Bullet(text: 'HackerRank: ${extraDetails['hackerrank'] ?? 'N/A'}'),
            ],

            pw.Footer(
              padding: const pw.EdgeInsets.only(top: 40),
              trailing: pw.Text('Generated by CodeSphere AI'),
            )
          ];
        },
      ),
    );

    final directory = await getApplicationDocumentsDirectory();
    final fileName = 'Resume_Summary_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File(p.join(directory.path, fileName));
    await file.writeAsBytes(await pdf.save());
    
    return file.path;
  }

  /// Saves the original resume file to a secure local directory.
  static Future<String> saveOriginalResume(File originalFile) async {
    final directory = await getApplicationDocumentsDirectory();
    final resumeDir = Directory(p.join(directory.path, 'resumes'));
    if (!await resumeDir.exists()) {
      await resumeDir.create(recursive: true);
    }

    final fileName = 'Original_${p.basename(originalFile.path)}';
    final savedFile = await originalFile.copy(p.join(resumeDir.path, fileName));
    return savedFile.path;
  }
}
