// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHoadg7lHZlgJFiNWw47XW3kY3kILcq3Y',
    appId: '1:168999871119:web:55d86e69708350b21c06fa',
    messagingSenderId: '168999871119',
    projectId: 'coding-tracker-app-d0224',
    authDomain: 'coding-tracker-app-d0224.firebaseapp.com',
    storageBucket: 'coding-tracker-app-d0224.firebasestorage.app',
    measurementId: 'G-V3Y0C53YYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0Vco6PLF3FDJ1UdS28bq7gp7eO8crX4',
    appId: '1:168999871119:android:958fb24040ad1b001c06fa',
    messagingSenderId: '168999871119',
    projectId: 'coding-tracker-app-d0224',
    storageBucket: 'coding-tracker-app-d0224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm1kJPyZObhVEvxIL_Skyc5adIjLN9MRE',
    appId: '1:168999871119:ios:877b317e8fca4e791c06fa',
    messagingSenderId: '168999871119',
    projectId: 'coding-tracker-app-d0224',
    storageBucket: 'coding-tracker-app-d0224.firebasestorage.app',
    iosClientId: '168999871119-3k9l8t422lpcllrekbcn46e2bgbgkfp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm1kJPyZObhVEvxIL_Skyc5adIjLN9MRE',
    appId: '1:168999871119:ios:877b317e8fca4e791c06fa',
    messagingSenderId: '168999871119',
    projectId: 'coding-tracker-app-d0224',
    storageBucket: 'coding-tracker-app-d0224.firebasestorage.app',
    iosClientId: '168999871119-3k9l8t422lpcllrekbcn46e2bgbgkfp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHoadg7lHZlgJFiNWw47XW3kY3kILcq3Y',
    appId: '1:168999871119:web:b7b2184e61fa1e8d1c06fa',
    messagingSenderId: '168999871119',
    projectId: 'coding-tracker-app-d0224',
    authDomain: 'coding-tracker-app-d0224.firebaseapp.com',
    storageBucket: 'coding-tracker-app-d0224.firebasestorage.app',
    measurementId: 'G-YDWWHNTPWE',
  );
}
